### ISSUE TITLE
Detectar cuando cambiar de turno en un canto "quiero" o "no quiero"

### ISSUE THREAD

**Issue by ignacioFernandez1** [ignacioFernandez1/Trucardo#5]
Para el truco y retruco lo podemos hacer asi: cuando un jugador canta quiero siempre cambiamos de turno excepto cuando en la pila no hay un "truco querido". Asi cuando yo cante Truco, se suma a la pila "truco","necesita respuesta" y el otro jugador canta "retruco" (se borra necesita respuesta y se pone retruco). Cuando yo cante quiero, como no va a haber un "truco querido" no va a cambiar de turno el quiero

**Comment by francomlopez** [comment]
Se llego a la solucion implementando una nueva variable de jugador que permita llevar quien puede cantar.
